#config_version=4
mode:
  start_events: start_warp_ramp_multiball_request
  stop_events: multiball_plaid_multiball_ended
  priority: 1000

event_player:
  warp_ramp_shot_jackpotpending_hit: warp_ramp_mb_award_jackpot
show_player:
  multiball_plaid_multiball_started:
    ball_saver_timer_show:
      loops: 0
      speed: 1    
  multiball_plaid_multiball_ended:
    ball_saver_timer_show:
      action: stop

#start_sbone_multiball_request

sound_player:
  warp_ramp_mb_award_jackpot:
    jackpot_2:
      action: play

scoring:
  warp_ramp_mb_award_jackpot:
    score: 500000 * current_player.game_scoring_multiplier

multiballs:
  plaid_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 10s
    start_events: mode_warp_ramp_multiball_started

shots:
  warp_ramp_shot:
    profile: warp_ramp_mb_jackpot_shot_profile

shot_profiles:
  warp_ramp_mb_jackpot_shot_profile:
    states:
      - name: jackpotpending
        loops: -1
        show: warp_ramp_mb_jackpot_pending

slide_player:
  warp_ramp_mb_award_jackpot:
    warp_ramp_mb_jackpot_achieved_slide:
      target: dmd
      expire: 1

slides:
  warp_ramp_mb_jackpot_achieved_slide:
    widgets:
      - type: text
        text: JACKPOT
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 500,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 00aa00
