#config_version=4
mode:
  start_events: ball_starting
  priority: 1000

show_player:
  mode_warp_ramp_multiball_started:
    warp_ramp_level_pending:
      loops: -1
      speed: 8
      show_tokens:
        ramp_level: rgb_ramplevel_1
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==1}:
    warp_ramp_level_pending:
      loops: -1
      speed: 8
      show_tokens:
        ramp_level: rgb_ramplevel_2
    warp_ramp_lightspeed_complete:
      loops: -1
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==2}:
    warp_ramp_level_pending:
      loops: -1
      speed: 8
      show_tokens:
        ramp_level: rgb_ramplevel_3
    warp_ramp_ridiculous_complete:
      loops: -1
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==3}:
    warp_ramp_level_pending:
      loops: -1
      speed: 8
      show_tokens:
        ramp_level: rgb_ramplevel_4
    warp_ramp_ludicrous_complete:
      loops: -1
  logicblock_warp_ramp_level_counter_complete:
    warp_ramp_level_pending:
      action: stop
    warp_ramp_plaid_complete:
      loops: -1
    
scoring:
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==1}:
    score: 100000
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==2}:
    score: 200000
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==3}:
    score: 300000
  logicblock_warp_ramp_level_counter_complete:
    score: 1000000

slide_player:
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==1}:
    warp_ramp_lightspeed_achieved_slide:
      target: dmd
      expire: 2
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==2}:
    warp_ramp_ridiculousspeed_achieved_slide:
      target: dmd
      expire: 2
  logicblock_warp_ramp_level_counter_hit{current_player.warp_ramp_level_counter_count==3}:
    warp_ramp_ludicrousspeed_achieved_slide:
      target: dmd
      expire: 2
  logicblock_warp_ramp_level_counter_complete:
    warp_ramp_plaid_achieved_slide:
      target: dmd
      expire: 2

multiballs:
    plaid_multiball:
        ball_count: 3
        ball_count_type: total
        shoot_again: 20s
        start_events: logicblock_warp_ramp_level_counter_complete
    
logic_blocks:
  counters:
    warp_ramp_level_counter:
      count_events: warp_ramp_shot_hit
      count_complete_value: 4
      disable_on_complete: true
      enable_events: mode_warp_ramp_multiball_started
      disable_events: mode_warp_ramp_multiball_stopped
      reset_events: mode_warp_ramp_multiball_started

slides:
  warp_ramp_lightspeed_achieved_slide:
    widgets:
      - type: text
        text: LIGHT SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 100,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 00aa00
  warp_ramp_ridiculousspeed_achieved_slide:
    widgets:
      - type: text
        text: RIDICULOUS SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 200,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: a38a18
  warp_ramp_ludicrousspeed_achieved_slide:
    widgets:
      - type: text
        text: LUDICROUS SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 300,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 880000
  warp_ramp_plaid_achieved_slide:
    widgets:
      - type: text
        text: PLAID MULTIBALL
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 1,000,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: image
        image: goneplaid_frame1
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0


shots:
  warp_ramp_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s