#config_version=4
mode:
  start_events: ball_starting
  priority: 1000

shots:
  warp_ramp_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
  warp_ramp_lightspeed_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    profile: warp_ramp_lightspeed_profile
    disable_events: warp_ramp_level_lightspeed_achieved
    enable_events: warp_ramp_lightspeed_pending_activate
  warp_ramp_ridiculousspeed_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    profile: warp_ramp_ridiculousspeed_profile
    disable_events: warp_ramp_level_ridiculousspeed_achieved
    enable_events: warp_ramp_ridiculousspeed_pending_activate
  warp_ramp_ludicrousspeed_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    profile: warp_ramp_ludicrousspeed_profile
    disable_events: warp_ramp_level_ludicrousspeed_achieved
    enable_events: warp_ramp_ludicrousspeed_pending_activate
  warp_ramp_plaidspeed_shot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    profile: warp_ramp_plaidspeed_profile
    disable_events: warp_ramp_level_plaidspeed_achieved
    enable_events: warp_ramp_plaidspeed_pending_activate

shot_groups:
  warp_ramp_shots:
    shots: warp_ramp_lightspeed_shot, warp_ramp_ridiculousspeed_shot, warp_ramp_ludicrousspeed_shot, warp_ramp_plaidspeed_shot
    reset_events: warp_ramp_shots_complete
    enable_events: ball_started
    disable_events: ball_ending

shot_profiles:
  warp_ramp_lightspeed_profile:
    states:
      - name: unlit
        show: warp_ramp_lightspeed_pending
        loops: -1
      - name: lit
        show: warp_ramp_lightspeed_complete
  warp_ramp_ridiculousspeed_profile:
    states:
      - name: unlit
        show: warp_ramp_ridiculousspeed_pending
        loops: -1
      - name: lit
        show: warp_ramp_ridiculousspeed_complete
  warp_ramp_ludicrousspeed_profile:
    states:
      - name: unlit
        show: warp_ramp_ludicrousspeed_pending
        loops: -1
      - name: lit
        show: warp_ramp_ludicrousspeed_complete
  warp_ramp_plaidspeed_profile:
    states:
      - name: unlit
        show: warp_ramp_plaidspeed_pending
        loops: -1
      - name: lit
        show: warp_ramp_plaidspeed_complete

show_player:
  multiball_plaid_multiball_started:
    ball_saver_timer_show:
      loops: 0
      speed: 1    
  multiball_plaid_multiball_ended:
    ball_saver_timer_show:
      action: stop


sound_player:
  warp_ramp_level_lightspeed_achieved:
    lightspeed_2:
      action: play
  warp_ramp_level_ridiculousspeed_achieved:
    ridiculous_speed_1:
      action: play
  warp_ramp_level_ludicrousspeed_achieved:
    ludicrous_speed_1:
      action: play

event_player:
  warp_ramp_lightspeed_shot_unlit_hit: warp_ramp_level_lightspeed_achieved warp_ramp_ridiculousspeed_pending_activate
  warp_ramp_ridiculousspeed_shot_unlit_hit: warp_ramp_level_ridiculousspeed_achieved warp_ramp_ludicrousspeed_pending_activate
  warp_ramp_ludicrousspeed_shot_unlit_hit: warp_ramp_level_ludicrousspeed_achieved warp_ramp_plaidspeed_pending_activate
  warp_ramp_plaidspeed_shot_unlit_hit: warp_ramp_level_plaidspeed_achieved
  mode_warp_ramp_multiball_started: warp_ramp_lightspeed_pending_activate
  
scoring:
  warp_ramp_level_lightspeed_achieved:
    score: 100000 * current_player.game_scoring_multiplier
  warp_ramp_level_ridiculousspeed_achieved:
    score: 200000 * current_player.game_scoring_multiplier
  warp_ramp_level_ludicrousspeed_achieved:
    score: 300000 * current_player.game_scoring_multiplier
  warp_ramp_level_plaidspeed_achieved:
    score: 1000000 * current_player.game_scoring_multiplier

slide_player:
  warp_ramp_level_lightspeed_achieved:
    warp_ramp_lightspeed_achieved_slide:
      target: dmd
      expire: 2
    warp_ramp_lightspeed_achieved_videoslide:
      target: lcd
      expire: 3200ms
  warp_ramp_level_ridiculousspeed_achieved:
    warp_ramp_ridiculousspeed_achieved_slide:
      target: dmd
      expire: 2
    warp_ramp_ridiculousspeed_achieved_videoslide:
      target: lcd
      expire: 3300ms
  warp_ramp_level_ludicrousspeed_achieved:
    warp_ramp_ludicrousspeed_achieved_slide:
      target: dmd
      expire: 2
    warp_ramp_ludicrousspeed_achieved_videoslide:
      target: lcd
      expire: 5200ms
  warp_ramp_level_plaidspeed_achieved:
    warp_ramp_plaid_achieved_slide:
      target: dmd
      expire: 2
    warp_ramp_plaid_achieved_videoslide:
      target: lcd
      expire: 4300ms

multiballs:
  plaid_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 10s
    start_events: warp_ramp_level_plaidspeed_achieved
    
logic_blocks:
  counters:
    warp_ramp_level_counter:
      count_events: warp_ramp_shot_hit
      count_complete_value: 4
      disable_on_complete: true
      enable_events: mode_warp_ramp_multiball_started multiball_plaid_multiball_ended
      disable_events: multiball_plaid_multiball_started
      reset_events: multiball_plaid_multiball_ended
      persist_state: true

slides:
  warp_ramp_lightspeed_achieved_videoslide:
    widgets:
      - type: video
        video: start_lightspeed
        width: 1280
        height: 720
  warp_ramp_lightspeed_achieved_slide:
    widgets:
      - type: text
        text: LIGHT SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 100,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 00aa00
  warp_ramp_ridiculousspeed_achieved_videoslide:
    widgets:
      - type: video
        video: darkhelmet_lightspeed_flying
        width: 1280
        height: 720
  warp_ramp_ridiculousspeed_achieved_slide:
    widgets:
      - type: text
        text: RIDICULOUS SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 200,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: a38a18
  warp_ramp_ludicrousspeed_achieved_videoslide:
    widgets:
      - type: video
        video: brains_in_my_feet
        width: 1280
        height: 720
  warp_ramp_ludicrousspeed_achieved_slide:
    widgets:
      - type: text
        text: LUDICROUS SPEED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 300,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 880000
  warp_ramp_plaid_achieved_videoslide:
    widgets:
      - type: video
        video: theyve_gone_to_plaid
        width: 1280
        height: 720
  warp_ramp_plaid_achieved_slide:
    widgets:
      - type: text
        text: PLAID MULTIBALL
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 3
        x: center
        color: ffffff
      - type: text
        text: 1,000,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 3
        x: center
        color: ffffff
      - type: image
        image: goneplaid_frame1
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
