#config_version=4

show_player:
  mode_attract_started:
    flash_start_button:
      loops: -1
      speed: 1
    attract_dmd_loop:
      loops: -1
      speed: 1
    flowing_s_loop:
      loops: -1
      speed: 1
    quick_alternating:
      loops: -1
      speed: 2
    three_crawl:
      loops: -1
      speed: 3
    drop_target_crawl:
      loops: -1
      speed: 4
    ramp_crawl:
      loops: -1
      speed: 1
    schwartz_level_crawl:
      loops: -1
      speed: 5
    ball_saver_crawl:
      loops: -1
      speed: 10
#    attract_lcd_loop:
#      loops: -1
#      speed: 1



#dead flip code
#Both, 4L, 1R, 5L, 1R, 1L, 2R
# combo_switches:
  # both_flippers_code:
    # switches_1: s_left_flipper
    # switches_2: s_right_flipper

# logic_blocks:
  # counters:
    # attract_code_state_counter:
      # count_events: attract_code_state_step
      # count_complete_value: 2
      # disable_on_complete: false
      # enable_events: mode_attract_started
      # reset_events: bad_attract_code_entry

# timers:
  # attract_code_entry_timer:
    # start_value: 20
    # end_value: 0
    # tick_interval: 1s
    # direction: down
    # control_events:
      # - action: start
        # event: both_flippers_code_hit
      # - action: reset
        # event: both_flippers_code_hit

# event_player:
  # both_flippers_code_hit: attract_code_state_step
  # timer_attract_code_entry_timer_complete: bad_attract_code_entry

# shots:
  # dead_flip_code:
    # switch_sequence: s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_right_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_right_flipper, s_left_flipper, s_right_flipper, s_right_flipper
    # time: 20s
    # enable_events: both_flippers_code_hit
    # disable_events: bad_attract_code_entry
    # reset_events: both_flippers_code_hit

# slide_player:
  # dead_flip_code_hit:
    # dead_flip_mode_activated:
      # target: dmd
      # expire: 1s

# slides:
  # dead_flip_mode_activated:
    # widgets:
      # - type: image
        # image: dead_flip_fill
        # anchor_y: bottom
        # anchor_x: left
        # y: 0
        # x: 0
