#config_version=4

show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
      speed: 1
    flowing_s_loop:
      loops: -1
      speed: 1
    quick_alternating:
      loops: -1
      speed: 2
    three_crawl:
      loops: -1
      speed: 3
    drop_target_crawl:
      loops: -1
      speed: 4
    ramp_crawl:
      loops: -1
      speed: 1
    schwartz_level_crawl:
      loops: -1
      speed: 5
    ball_saver_crawl:
      loops: -1
      speed: 10
#    attract_lcd_loop:
#      loops: -1
#      speed: 1
