#config_version=4
mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    slide_1:
      target: dmd

scoring:
  s_sling_right_active:
    score: 10000
  s_sling_left_active:
    score: 10000
  s_pop_1_active:
    score: 10000
  s_pop_2_active:
    score: 10000
  s_pop_3_active:
    score: 10000
  s_drop_1_active:
    score: 50000
  s_drop_2_active:
    score: 50000
  s_drop_3_active:
    score: 50000
  s_drop_4_active:
    score: 50000
  s_drop_5_active:
    score: 50000

slides:
  slide_1:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    color: 0099ff
    x: left
    y: bottom
  - type: text
    text: BALL (ball)
    anchor_y: bottom
    anchor_x: right
    style: small
    color: 0099ff
    x: right
    y: bottom
