#config_version=4
mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    slide_1:
      transition:
        type: move_in
scoring:
  s_left_slingshot_active:
    score: 10000
  s_right_slingshot_active:
    score: 10000

sound_player:
  balldevice_bd_trough_ball_eject_attempt: greathelmet
slides:
  slide_1:
  - type: text
    text: (score)
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)
    anchor_y: bottom
    anchor_x: left
    style: small
    color: 0099ff
    x: left
    y: bottom
  - type: text
    text: BALL (ball)
    anchor_y: bottom
    anchor_x: right
    style: small
    color: 0099ff

    x: right
    y: bottom
