#config_version=4
mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    player_info_slide:
      target: dmd
  ball_save_default_save_saving_ball:
    ball_saved_slide:
      target: dmd
      expire: 1

show_player:
  ball_save_default_save_timer_start:
    ball_saver_timer_show:
      loops: 0
      speed: 1    

scoring:
  s_sling_right_active:
    score: 10000
  s_sling_left_active:
    score: 10000
  s_pop_1_active:
    score: 10000
    pophits: 1
  s_pop_2_active:
    score: 10000
    pophits: 1
  s_pop_3_active:
    score: 10000
    pophits: 1
  s_drop_1_active:
    score: 50000
  s_drop_2_active:
    score: 50000
  s_drop_3_active:
    score: 50000
  s_drop_4_active:
    score: 50000
  s_drop_5_active:
    score: 50000

sound_player:
  ball_save_default_save_saving_ball:
    ball_saved_2:
      action: play

slides:
  ball_saved_slide:
    widgets:
      - type: text
        text: BALL SAVED
        style: dmd_big
        x: center
        y: center
        anchor_x: center
        anchor_y: center
  player_info_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        style: dmd_big
        x: center
        y: top - 5
        anchor_x: center
        anchor_y: top
      - type: text
        text: PLAYER (number)
        y: 0
        x: 0
        style: dmd_small
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right
        anchor_x: right
        anchor_y: bottom
        style: dmd_small
#      - type: text
#        text: "ss: (skillshot_level_counter_count)"
#        style: dmd_small
#        y: 40%