#config_version=4
mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started:
    slide_1:
      target: dmd

scoring:
  s_sling_right_active:
    score: 10000
  s_sling_left_active:
    score: 10000
  s_pop_1_active:
    score: 10000
  s_pop_2_active:
    score: 10000
  s_pop_3_active:
    score: 10000
  s_drop_1_active:
    score: 50000
  s_drop_2_active:
    score: 50000
  s_drop_3_active:
    score: 50000
  s_drop_4_active:
    score: 50000
  s_drop_5_active:
    score: 50000
    
slides:
  slide_1:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        style: dmd_big
        x: center
        y: top - 5
        anchor_x: center
        anchor_y: top
      - type: text
        text: PLAYER (number)
        y: 0
        x: 0
        style: dmd_small
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right
        anchor_x: right
        anchor_y: bottom
        style: dmd_small
#      - type: text
#        text: "ss: (skillshot_level_counter_count)"
#        style: dmd_small
#        y: 40%