#config_version=3
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    - type: text
      text: "%score%"
      number_grouping: true
      min_digits: 2
      v_pos: center
      transition:
          type: move_in
    - type: text
      text: PLAYER %number%
      v_pos: bottom
      h_pos: left
      font: small
      color: 0099ff
    - type: text
      text: BALL %ball%
      v_pos: bottom
      h_pos: right
      font: small
      color: 0099ff

scoring:
    s_left_slingshot_active:
        score: 10000
    s_right_slingshot_active:
        score: 10000

sound_player:
    ball_launch_whoosh:
        sound: greathelmet
        start_events: balldevice_bd_trough_ball_eject_attempt
