#config_version=4
mode:
  start_events: start_airlock_multiball_request start_warp_ramp_multiball_request start_sbone_multiball_request
  stop_events: stop_airlock_multiball_request stop_warp_ramp_multiball_request stop_sbone_multiball_request
  priority: 400
  code: sbone_autoeject.sbone_autoeject
