#config_version=4
mode:
  start_events: mode_attract_started
  stop_events: mode_attract_stopped
  priority: 400
  game_mode: false
  code: dead_flip.dead_flip


#dead flip code
#Both, 4L, 1R, 5L, 1R, 1L, 2R
# combo_switches:
  # both_flippers_code:
    # switches_1: s_left_flipper
    # switches_2: s_right_flipper

# logic_blocks:
  # counters:
    # deadflip_code_state_counter:
      # count_events: deadflip_code_state_increment
      # count_complete_value: 10
      # disable_on_complete: false
      # enable_events: mode_dead_flip_started
      # reset_events: bad_deadflip_code_entry

# event_player:
  # s_left_flipper_active: deadflip_code_state_increment

# timers:
  # attract_code_entry_timer:
    # start_value: 20
    # end_value: 0
    # tick_interval: 1s
    # direction: down
    # control_events:
      # - action: start
        # event: both_flippers_code_hit
      # - action: reset
        # event: both_flippers_code_hit

# event_player:
  # both_flippers_code_hit: attract_code_state_step
  # timer_attract_code_entry_timer_complete: bad_attract_code_entry

# shots:
  # dead_flip_code:
    # switch_sequence: s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_right_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_left_flipper, s_right_flipper, s_left_flipper, s_right_flipper, s_right_flipper
    # time: 20s
    # enable_events: both_flippers_code_hit
    # disable_events: bad_attract_code_entry
    # reset_events: both_flippers_code_hit

# slide_player:
  # dead_flip_code_hit:
    # dead_flip_mode_activated:
      # target: dmd
      # expire: 1s

# slides:
  # dead_flip_mode_activated:
    # widgets:
      # - type: image
        # image: dead_flip_fill
        # anchor_y: bottom
        # anchor_x: left
        # y: 0
        # x: 0

