#config_version=4
mode:
  start_events: ball_starting
  stop_events: player_turn_ending
  priority: 100

shot_groups:
  airlock_targets_easy:
    profile: airlock_lights_easy
    enable_events: ball_started
    disable_events: ball_ending
