#config_version=4

mode:
  start_events: start_sbone_multiball_mode_request
  stop_events: stop_sbone_multiball_mode_request
  priority: 1300

event_player:
  multiball_sbone_multiball_ended: sbone_multiball_complete|50ms

