#config_version=4

mode:
  start_events: start_sbone_multiball_mode_request
  stop_events: stop_sbone_multiball_mode_request
  priority: 1300

event_player:
  multiball_sbone_multiball_ended: sbone_multiball_complete|50ms

multiball_locks:
  sbone_mb_lock:
    balls_to_lock: 3
    lock_devices: bd_sbone
    reset_count_for_current_player_events: multiball_sbone_multiball_ended