#config_version=3

hardware:
    platform: smart_virtual
    driverboards: virtual
    dmd: smartmatrix

config:
    - portconfig.yaml
    - switches.yaml
    - coils.yaml
    - devices.yaml
    - keyboard.yaml
    - virtual.yaml
    - images.yaml

dmd:
    physical: yes
    width: 128
    height: 32
    type: color

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2

#slide_player:
#    mode_attract_started:
#        type: text
#        text: PRESS START
#        slide_priority: 10
#        color: 0099ff

modes:
    - base
