#config_version=4

game:
  balls_per_game: 1

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

physical_rgb_dmds:
  my_dmd:
     platform: smartmatrix
     brightness: 1.0
     fps: 20

fast:
  config_number_format: int
  
config:
- portconfig.yaml
- switches.yaml
- coils.yaml
- leds.yaml
- devices.yaml
- keyboard.yaml
- virtual.yaml
- images.yaml
- videos.yaml

modes:
- base
- skillshot_timing
- bonus
- high_score
- warp_ramp_multiball
- spinner

sound_system:
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 1
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
    sfx:
      volume: 1
      priority: 1
      simultaneous_sounds: 3
    music:
      volume: 0.5
      simultaneous_sounds: 1
  enabled: true

assets:
    sounds:
        default:
            load: preload
        voice:
            load: preload
            track: voice
        sfx:
            load: preload
            track: sfx
        music:
            load: preload
            track: music

sounds:
  spaceballs_song:
    target: music

sound_player:
  mode_base_started:
    spaceballs_song:
      action: play

  ball_ending:
    spaceballs_song:
      action: stop

displays:
  lcd:
    width: 1360
    height: 768
  dmd:
    width: 128
    height: 32
    default: true
    
window:
  width: 1360 
  height: 768
  #fullscreen: true
  borderless: true
  #width: 640
  #height: 360
  #fullscreen: false
  #borderless: false
  title: Spaceballs
  resizable: false
  exit_on_escape: true
  source_display: lcd

player_vars:
  bonus_multiplier:
    initial_value: 1
  pophits:
    initial_value: 0
    
ball_saves:
  default_save:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_trough_ball_eject_success
    auto_launch: yes
    balls_to_save: 1
    debug: yes
  
#slides:
#  lcd_main_video:
#    widgets:
#      - type: video
#        video: introcrawl
#        width: 1280
#        height: 720
    
#slide_player:
#  machine_reset_phase_3:
#    lcd_main_video:
#      target: lcd
