#config_version=4

game:
  balls_per_game: 1

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

physical_rgb_dmds:
  my_dmd:
     platform: smartmatrix
     brightness: 1.0
     fps: 20

fast:
  config_number_format: int
  
config:
- portconfig.yaml
- switches.yaml
- coils.yaml
- leds.yaml
- devices.yaml
- keyboard.yaml
- virtual.yaml
- images.yaml
- videos.yaml
- sounds.yaml

modes:
- base
- skillshot_timing
- bonus
- high_score
- warp_ramp_multiball
- spinner
- diner
- airlock_multiball
- pops_base
- air_lanes

widget_styles:
  dmd_xl:
      font_name: Quadrit
      font_size: 15
      adjust_bottom: 7
      adjust_top: 3

sound_system:
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 1
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
    sfx:
      volume: 1
      priority: 1
      simultaneous_sounds: 3
    music:
      volume: 0.5
      simultaneous_sounds: 1
  enabled: true

displays:
  lcd:
    width: 1360
    height: 768
  dmd:
    width: 128
    height: 32
    default: true

window:
  width: 1360 
  height: 768
  #fullscreen: true
  borderless: true
  title: Spaceballs
  resizable: false
  exit_on_escape: true
  source_display: lcd

player_vars:
  game_scoring_multiplier:
    initial_value: 1
  bonus_multiplier:
    initial_value: 1
  pophits:
    initial_value: 0

#slide_player:
#  player_add_request:
#    player_add_videos:
#      target: lcd
#      expire: 2s

slides:
  player_add_video:
    widgets:
      - type: video
        video: player_add_videos
        width: 1280
        height: 720
        volume: 0.5

video_pools:
  player_add_videos:
    type: random_force_next
    videos:
      - gunners_mate_phillip_asshole
      - hail_skroob
      - hello_lonestar_1
      - hello_lonestar_2
      - hes_an_asshole_sir
      - hes_an_asshole_too
      - how_many_assholes_we_got
      - surrounded_by_assholes
      - major_asshole

ball_saves:
  default_save:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 1s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_trough_ball_eject_success
    auto_launch: yes
    balls_to_save: 1

