# config_version=4

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

autofire_coils:
  af_leftsling:
    coil: c_sling_left  
    switch: s_sling_left
  af_rightsling:
    coil: c_sling_right  
    switch: s_sling_right
  af_pop_1:
    coil: c_pop_1
    switch: s_pop_1
  af_pop_2:
    coil: c_pop_2
    switch: s_pop_2
  af_pop_3:
    coil: c_pop_3
    switch: s_pop_3

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    entrance_count_delay: 300ms
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain
    debug: true
  bd_plunger:
    ball_switches: s_plunger_lane
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    tags: ball_add_live
    eject_coil: c_plunger_eject
    player_controlled_eject_event: sw_launch
  bd_saucer:
    label: Saucer Kickout
    ball_switches: s_saucer
    entrance_count_delay: 1.0s
    eject_coil: c_saucer_eject
    exit_count_delay: 250ms
  bd_scoop:
    label: Scoop Kickout
    ball_switches: s_scoop
    entrance_count_delay: 1.0s
    eject_coil: c_scoop_eject
    exit_count_delay: 250ms

