#config_version=4

assets:
  sounds:
    default:
      load: preload
    voice:
      load: preload
      track: voice
    sfx:
      load: preload
      track: sfx
    music:
      load: preload
      track: music

sounds:
  spaceballs_song:
    target: music
    volume: 0.70
  skillshot_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  game_over_3:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 1.0 sec
      release: 1.0 sec
  lightspeed_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ridiculous_speed_1:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ludicrous_speed_1:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ball_saved_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
