# config_version=4

switches:
  s_left_flipper:
    number: 0
  s_right_flipper:
    number: 1
  s_trough1:
    number: 2
  s_trough2:
    number: 3
  s_trough3:
    number: 4
  s_trough4:
    number: 5
  s_trough5:
    number: 6
  s_trough6:
    number: 7
  s_trough_jam:
    number: 8
  s_plunger_lane:
    number: 9
  s_launch_button:
    number: 10
    tags: launch
  s_start:
    number: 11
    tags: start
  s_right_inlane:
    number: 12
    tags: playfield_active
  s_left_slingshot:
    number: 13
    tags: playfield_active, slingshot
  s_right_slingshot:
    number: 14
    tags: playfield_active, slingshot
  s_airlock_1:
    number: 15
  s_airlock_2:
    number: 16
  s_airlock_3:
    number: 17
  s_airlock_4:
    number: 18
  s_airlock_5:
    number: 19
