# config_version=4

switches:
  s_right_flipper:
    number: 0
  s_launch_button:
    number: 1
    tags: launch
  s_left_flipper:
    number: 2
  s_start:
    number: 3
    tags: start
  s_trough1:
    number: 8
    type: NC
  s_trough2:
    number: 9
    type: NC
  s_trough3:
    number: 10
    type: NC
  s_trough4:
    number: 11
    type: NC
  s_trough5:
    number: 12
    type: NC
  s_trough6:
    number: 13
    type: NC
  s_trough_jam:
    number: 14
    type: NC
  s_plunger_lane:
    number: 15
  s_saucer:
    number: 16
  s_scoop:
    number: 17
  s_drop_1:
    number: 18
  s_drop_2:
    number: 19
  s_drop_3:
    number: 20
  s_drop_4:
    number: 21
  s_drop_5:
    number: 22
  s_sling_right:
    number: 24
  s_sling_left:
    number: 25
  s_pop_1:
    number: 40
  s_pop_2:
    number: 41
  s_pop_3:
    number: 42
