#config_version=4
mode:
  start_events: game_starting
  priority: 100

sound_player:
  mode_base_started:
    spaceballs_song:
      action: play
      priority: 100
  mode_bonus_started:
    spaceballs_song:
      action: stop
      fade_out: 2.5s
  start_base_music_request:
    spaceballs_song:
      action: play
      priority: 100
  resume_base_music_request:
    spaceballs_song:
      action: play
      priority: 100
      start_at: 7s
  stop_base_music_request:
    spaceballs_song:
      action: stop
  start_airlock_multiball_music_request:
    spaceballs_hot_together:
      action: play
      priority: 150
  stop_airlock_multiball_music_request:
    spaceballs_hot_together:
      action: stop
  start_barf_multiball_music_request:
    spaceballs_raise_your_hands:
      action: play
      priority: 151
  stop_barf_multiball_music_request:
    spaceballs_raise_your_hands:
      action: stop
