#config_version=4

mode:
  start_events: ball_starting
  priority: 1400

shots:
  airlock_shot_one:
    switch: s_drop_1
    profile: airlock_target_profile
    show_tokens:
       targetled: rgb_drop_1
  airlock_shot_two:
    switch: s_drop_2
    profile: airlock_target_profile
    show_tokens:
       targetled: rgb_drop_2
  airlock_shot_three:
    switch: s_drop_3
    profile: airlock_target_profile
    show_tokens:
       targetled: rgb_drop_3
  airlock_shot_four:
    switch: s_drop_4
    profile: airlock_target_profile
    show_tokens:
       targetled: rgb_drop_4
  airlock_shot_five:
    switch: s_drop_5
    profile: airlock_target_profile
    show_tokens:
       targetled: rgb_drop_5

shot_profiles:
  airlock_target_profile:
    states:
      - name: unlit
        show: airlock_target_pending
        loops: -1
      - name: lit
        show: airlock_target_on

shot_groups:
  airlock_drops:
    shots: airlock_shot_one, airlock_shot_two, airlock_shot_three, airlock_shot_four, airlock_shot_five
    reset_events: airlock_drops_complete
    enable_events: ball_started
    disable_events: ball_ending

multiballs:
  add_a_ball:
    ball_count: 1
    ball_count_type: add
    shoot_again: 10s
    enable_events: mode_airlock_multiball_started
    add_a_ball_events: airlock_multiball_gimme_another_ball
    disable_events: ball_ending
    start_events: airlock_drops_complete
    stop_events: ball_ending

slide_player:
  s_drop_1_active:
    airlock_one_complete_slide:
      target: dmd
      expire: 1
    airlock_one_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_2_active:
    airlock_two_complete_slide:
      target: dmd
      expire: 1
    airlock_two_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_3_active:
    airlock_three_complete_slide:
      target: dmd
      expire: 1
    airlock_three_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_4_active:
    airlock_four_complete_slide:
      target: dmd
      expire: 1
    airlock_four_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_5_active:
    airlock_five_complete_slide:
      target: dmd
      expire: 1
    airlock_five_complete_slide_king:
      target: lcd
      expire: 1000ms

scoring:
  s_drop_1_active:
    score: 50000 * current_player.game_scoring_multiplier
  s_drop_2_active:
    score: 50000 * current_player.game_scoring_multiplier
  s_drop_3_active:
    score: 50000 * current_player.game_scoring_multiplier
  s_drop_4_active:
    score: 50000 * current_player.game_scoring_multiplier
  s_drop_5_active:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_drops_complete:
    score: 1000000 * current_player.game_scoring_multiplier

slides:
  airlock_one_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_one
        width: 1280
        height: 720
  airlock_one_complete_slide:
    widgets:
      - type: text
        text: 1
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_two_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_two
        width: 1280
        height: 720
  airlock_two_complete_slide:
    widgets:
      - type: text
        text: 2
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_three_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_three
        width: 1280
        height: 720
  airlock_three_complete_slide:
    widgets:
      - type: text
        text: 3
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_four_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_four
        width: 1280
        height: 720
  airlock_four_complete_slide:
    widgets:
      - type: text
        text: 4
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_five_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_five
        width: 1280
        height: 720
  airlock_five_complete_slide:
    widgets:
      - type: text
        text: 5
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
