#config_version=4

mode:
  start_events: ball_starting
  priority: 1400

show_player:
  mode_airlock_multiball_started:
    airlock_one_ready:
      loops: -1
      speed: 1
    airlock_two_ready:
      loops: -1
      speed: 1
    airlock_three_ready:
      loops: -1
      speed: 1
    airlock_four_ready:
      loops: -1
      speed: 1
    airlock_five_ready:
      loops: -1
      speed: 1
  s_drop_1_active:
    airlock_one_ready:
      action: stop
    airlock_one_lit:
      loops: -1
      speed: 1
  s_drop_2_active:
    airlock_two_ready:
      action: stop
    airlock_two_lit:
      loops: -1
      speed: 1
  s_drop_3_active:
    airlock_three_ready:
      action: stop
    airlock_three_lit:
      loops: -1
      speed: 1
  s_drop_4_active:
    airlock_four_ready:
      action: stop
    airlock_four_lit:
      loops: -1
      speed: 1
  s_drop_5_active:
    airlock_five_ready:
      action: stop
    airlock_five_lit:
      loops: -1
      speed: 1

slide_player:
  s_drop_1_active:
    airlock_one_complete_slide:
      target: dmd
      expire: 1
    airlock_one_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_2_active:
    airlock_two_complete_slide:
      target: dmd
      expire: 1
    airlock_two_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_3_active:
    airlock_three_complete_slide:
      target: dmd
      expire: 1
    airlock_three_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_4_active:
    airlock_four_complete_slide:
      target: dmd
      expire: 1
    airlock_four_complete_slide_king:
      target: lcd
      expire: 800ms
  s_drop_5_active:
    airlock_five_complete_slide:
      target: dmd
      expire: 1
    airlock_five_complete_slide_king:
      target: lcd
      expire: 1000ms

scoring:
  s_drop_1_active:
    score: 50000
  s_drop_2_active:
    score: 50000
  s_drop_3_active:
    score: 50000
  s_drop_4_active:
    score: 50000
  s_drop_5_active:
    score: 50000

slides:
  airlock_one_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_one
        width: 1280
        height: 720
  airlock_one_complete_slide:
    widgets:
      - type: text
        text: 1
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_two_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_two
        width: 1280
        height: 720
  airlock_two_complete_slide:
    widgets:
      - type: text
        text: 2
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_three_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_three
        width: 1280
        height: 720
  airlock_three_complete_slide:
    widgets:
      - type: text
        text: 3
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_four_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_four
        width: 1280
        height: 720
  airlock_four_complete_slide:
    widgets:
      - type: text
        text: 4
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
  airlock_five_complete_slide_king:
    widgets:
      - type: video
        video: airlock_king_five
        width: 1280
        height: 720
  airlock_five_complete_slide:
    widgets:
      - type: text
        text: 5
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
      - type: image
        image: planet_druidia
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
