# config_version=3


mode:
    start_events: start_airlock_multiball
    stop_events: timer_mode_timer_complete, ball_ended
    priority: 300

timers:
    mode_timer:
        start_events: start_airlock_multiball
        start_value: 10
        start_paused: yes
        end_value: 0
        direction: down
        tick_interval: 1s
        control_events:
          - event: start_airlock_multiball
            action: start

slide_player:
  mode_airlock_multiball_started:
    - type: text
      text: "AIRLOCK MULTIBALL"
      v_pos: center
      transition:
          type: move_in

