# config_version=4


mode:
  start_events: start_airlock_multiball
  stop_events: timer_mode_timer_complete, ball_ended
  priority: 300

timers:
  mode_timer:
    start_events: start_airlock_multiball
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
    - event: start_airlock_multiball
      action: start 

    start_running: false
show_player:
  mode_airlock_multiball_started:
    gone_to_plaid:
      loops: -1
      speed: 20
