#config_version=4

mode:
  start_events: start_airlock_multiball_mode_request
  stop_events: stop_airlock_multiball_mode_request
  priority: 1100

scoring:
  airlock_multiball_award_100k_shot:
    score: 100000 * current_player.game_scoring_multiplier
  airlock_multiball_gimme_another_ball:
    score: 250000 * current_player.game_scoring_multiplier

shots:
  airlock_mb_shot_one:
    switch: s_drop_1
    profile: airlock_mb_target_one_profile
    disable_events: activate_airlock_addaball_shot_1
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_shot_two:
    switch: s_drop_2
    profile: airlock_mb_target_two_profile
    disable_events: activate_airlock_addaball_shot_2
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_shot_three:
    switch: s_drop_3
    profile: airlock_mb_target_three_profile
    disable_events: activate_airlock_addaball_shot_3
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_shot_four:
    switch: s_drop_4
    profile: airlock_mb_target_four_profile
    disable_events: activate_airlock_addaball_shot_4
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_shot_five:
    switch: s_drop_5
    profile: airlock_mb_target_five_profile
    disable_events: activate_airlock_addaball_shot_5
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_shot_left_orbit:
    switch_sequence: s_left_spinner, s_right_orbit
    time: 2s
    profile: airlock_mb_generic_target_profile
    show_tokens:
        targetled: rgb_left_orbit_arrow_1
  airlock_mb_warp_ramp_shot:
    profile: airlock_mb_warpramp_target_profile
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    disable_events: activate_airlock_addaball_shot_6
    enable_events: activate_next_airlock_addaball_shot multiball_airlock_add_a_ball_started
  airlock_mb_scoop_shot:
    profile: airlock_mb_generic_target_profile
    switch: s_scoop
    show_tokens:
        targetled: rgb_scoop_arrow_1
  airlock_addaball_shot_one:
    switch: s_drop_1
    profile: airlock_addaball_target_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_1
    show_tokens:
       targetled: rgb_drop_1
  airlock_addaball_shot_two:
    switch: s_drop_2
    profile: airlock_addaball_target_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_2
    show_tokens:
       targetled: rgb_drop_2
  airlock_addaball_shot_three:
    switch: s_drop_3
    profile: airlock_addaball_target_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_3
    show_tokens:
       targetled: rgb_drop_3
  airlock_addaball_shot_four:
    switch: s_drop_4
    profile: airlock_addaball_target_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_4
    show_tokens:
       targetled: rgb_drop_4
  airlock_addaball_shot_five:
    switch: s_drop_5
    profile: airlock_addaball_target_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_5
    show_tokens:
       targetled: rgb_drop_5
  airlock_addaball_shot_six:
    switch_sequence: s_ramp_entry, s_ramp_exit
    time: 3s
    profile: airlock_addaball_warpramp_profile
    disable_events: activate_next_airlock_addaball_shot
    enable_events: activate_airlock_addaball_shot_6

event_player:
  multiball_airlock_add_a_ball_started: activate_next_airlock_addaball_shot
  airlock_addaball_shot_one_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_addaball_shot_two_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_addaball_shot_three_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_addaball_shot_four_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_addaball_shot_five_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_addaball_shot_six_hit: airlock_multiball_gimme_another_ball, activate_next_airlock_addaball_shot
  airlock_mb_shot_one_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_shot_two_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_shot_three_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_shot_four_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_shot_five_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_warp_ramp_shot_pending_hit: airlock_multiball_award_100k_shot
  airlock_mb_scoop_shot_pending_hit: airlock_multiball_award_100k_shot
  multiball_airlock_add_a_ball_ended: airlock_multiball_complete|50ms  

random_event_player:
  activate_next_airlock_addaball_shot:
    - activate_airlock_addaball_shot_1
    - activate_airlock_addaball_shot_2
    - activate_airlock_addaball_shot_3
    - activate_airlock_addaball_shot_4
    - activate_airlock_addaball_shot_5

shot_profiles:
  airlock_mb_target_one_profile:
    states:
      - name: pending
        show: airlock_mb_target_one_pending
        sync_ms: 500
        loops: -1
  airlock_mb_target_two_profile:
    states:
      - name: pending
        show: airlock_mb_target_two_pending
        sync_ms: 500
        loops: -1
  airlock_mb_target_three_profile:
    states:
      - name: pending
        show: airlock_mb_target_three_pending
        sync_ms: 500
        loops: -1
  airlock_mb_target_four_profile:
    states:
      - name: pending
        show: airlock_mb_target_four_pending
        sync_ms: 500
        loops: -1
  airlock_mb_target_five_profile:
    states:
      - name: pending
        show: airlock_mb_target_five_pending
        sync_ms: 500
        loops: -1
  airlock_mb_generic_target_profile:
    states:
      - name: pending
        show: airlock_mb_target_pending
        sync_ms: 500
        loops: -1
  airlock_mb_warpramp_target_profile:
    states:
      - name: pending
        show: airlock_mb_warpramp_pending
        sync_ms: 500
        loops: -1
  airlock_addaball_target_profile:
    states:
      - name: addaball_pending
        show: airlock_addaball_target_pending
        sync_ms: 500
        loops: -1
  airlock_addaball_warpramp_profile:
    states:
      - name: addaball_pending
        show: airlock_addaball_warpramp_pending
        sync_ms: 500
        loops: -1
